export const CUSTOM_FIELDS = [
  {
    name: "run_name",
    value: "run_name",
    alias: "RUN",
    type: "string",
    display: true,
    primary: true,
    children: [],
  },
  {
    name: "sample",
    value: "sample",
    alias: null,
    type: "object",
    display: false,
    primary: false,
    children: [
      {
        name: "organism",
        value: "sample.organism",
        alias: "Organism",
        type: "string",
        display: true,
        primary: false,
        children: [],
      },
    ],
  },
  {
    name: "experiment",
    value: "experiment",
    alias: null,
    type: "object",
    display: false,
    primary: false,
    children: [
      {
        name: "instrument",
        value: "experiment.instrument",
        alias: "Instrument (EXP)",
        type: "string",
        display: true,
        primary: false,
        children: [],
      },
      {
        name: "platform",
        alias: "Platform (EXP)",
        value: "experiment.platform",
        type: "string",
        display: true,
        primary: false,
        children: [],
      },
      {
        name: "libraryLayout",
        value: "experiment.libraryLayout",
        alias: "Library Layout (EXP)",
        type: "string",
        display: true,
        primary: false,
        children: [],
      },
      {
        name: "librarySource",
        value: "experiment.librarySource",
        alias: "Library Source (EXP)",
        type: "string",
        display: true,
        primary: false,
        children: [],
      },
    ],
  },
  {
    name: "stats_qc",
    value: "stats_qc",
    alias: "Stats QC",
    type: "object",
    display: false,
    primary: false,
    children: [
      {
        name: "total_bp",
        value: "stats_qc.total_bp",
        alias: "Total BP (QC)",
        type: "number",
        display: true,
        primary: false,
        children: [],
      },
    ],
  },
];
