/**
 * @author Jongil Yoon
 * @email jiysait@gmail.com
 * @create date 2021-07-25 14:52:52
 * @modify date 2021-07-25 14:52:52
 * @desc [description]
 */

/**
 * name: The original name of a data field
 * value: A value must reflect hierarchical structure
 * alias: A name will be displayed in the frontend app
 * display: A value indicates whether a column is enabled or not.
 * primary: A value indicates whether a column is primary or not.
 */
export const CUSTOM_HEADER_ASSEMBLY = {
  id: {
    name: "id",
    value: "id",
    alias: "ID",
    display: true,
    primary: true,
  },
  sequence: {
    name: "sequence",
    value: "sequence",
    alias: "Sequence",
    display: false,
    primary: false,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: false,
    primary: false,
  },
  sequence__project__id: {
    name: "id",
    value: "sequence__project__id",
    alias: "Project ID",
    display: true,
    primary: false,
  },
  sequence__project__title: {
    name: "title",
    value: "sequence__project__title",
    alias: "Project Title",
    display: true,
    primary: false,
  },
  sequence__LibrarySource: {
    name: "LibrarySource",
    value: "sequence__LibrarySource",
    alias: "Library Source",
    display: true,
    primary: false,
  },
  sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "sequence__LibraryLayout",
    alias: "Library Layout",
    display: true,
    primary: false,
  },
  sequence__SequencerModel: {
    name: "SequencerModel",
    value: "sequence__SequencerModel",
    alias: "Sequencer Model",
    display: true,
    primary: false,
  },
  sequence__CenterName: {
    name: "CenterName",
    value: "Sequence__CenterName",
    alias: "Center Name",
    display: true,
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Sequence Type",
    display: false,
    primary: false,
  },
  count: {
    name: "count",
    value: "count",
    alias: "Count",
    display: true,
    primary: false,
  },
  bp: {
    name: "bp",
    value: "bp",
    alias: "BP.",
    display: true,
    primary: false,
  },
  Ns: {
    name: "Ns",
    value: "Ns",
    alias: "Ns.",
    display: true,
    primary: false,
  },
  gaps: {
    name: "gaps",
    value: "gaps",
    alias: "Gaps",
    display: true,
    primary: false,
  },
  min: {
    name: "min",
    value: "min",
    alias: "Min.",
    display: true,
    primary: false,
  },
  max: {
    name: "max",
    value: "max",
    alias: "Max.",
    display: true,
    primary: false,
  },
  avg: {
    name: "avg",
    value: "avg",
    alias: "Avg.",
    display: true,
    primary: false,
  },
  N50: {
    name: "N50",
    value: "N50",
    alias: "N50",
    display: true,
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: true,
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: true,
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: false, // temporary disabled
    primary: false,
  },
};

export const CUSTOM_HEADER_SEQUENCE = {
  id: {
    name: "id",
    value: "id",
    alias: "ID",
    display: true,
    primary: true,
  },
  TaxID: {
    name: "TaxID",
    value: "TaxID",
    alias: "Tax ID",
    display: true,
    primary: false,
  },
  ScientificName: {
    name: "ScientificName",
    value: "ScientificName",
    alias: "Scientific Name",
    display: true,
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "seqtype",
    display: false,
    primary: false,
  },
  Experiment: {
    name: "Experiment",
    value: "Experiment",
    alias: "Experiment",
    display: true,
    primary: false,
  },
  LibraryName: {
    name: "LibraryName",
    value: "LibraryName",
    alias: "Library Name",
    display: true,
    primary: false,
  },
  LibraryStrategy: {
    name: "LibraryStrategy",
    value: "LibraryStrategy",
    alias: "Library Strategy",
    display: true,
    primary: false,
  },
  LibrarySelection: {
    name: "LibrarySelection",
    value: "LibrarySelection",
    alias: "Library Selection",
    display: true,
    primary: false,
  },
  LibrarySource: {
    name: "LibrarySource",
    value: "LibrarySource",
    alias: "Library Source",
    display: true,
    primary: false,
  },
  LibraryLayout: {
    name: "LibraryLayout",
    value: "LibraryLayout",
    alias: "Library Layout",
    display: true,
    primary: false,
  },
  Platform: {
    name: "Platform",
    value: "Platform",
    alias: "Platform",
    display: true,
    primary: false,
  },
  SequencerModel: {
    name: "SequencerModel",
    value: "SequencerModel",
    alias: "SequencerModel",
    display: true,
    primary: false,
  },
  Projectid: {
    name: "Projectid",
    value: "Projectid",
    alias: "Project ID",
    display: true,
    primary: false,
  },
  SampleName: {
    name: "SampleName",
    value: "SampleName",
    alias: "Sample Name",
    display: true,
    primary: false,
  },
  CenterName: {
    name: "CenterName",
    value: "CenterName",
    alias: "Center Name",
    display: true,
    primary: false,
  },
  taxName_1: {
    name: "taxName_1",
    value: "taxName_1",
    alias: "Tax Name 1",
    display: true,
    primary: false,
  },
  taxFrac_1: {
    name: "taxFrac_1",
    value: "taxFrac_1",
    alias: "Tax Frac 1",
    display: true,
    primary: false,
  },
  taxName_2: {
    name: "taxName_2",
    value: "taxName_2",
    alias: "Tax Name 2",
    display: true,
    primary: false,
  },
  taxFrac_2: {
    name: "taxFrac_2",
    value: "taxFrac_2",
    alias: "Tax Frac 2",
    display: true,
    primary: false,
  },
  taxName_3: {
    name: "taxName_3",
    value: "taxName_3",
    alias: "Tax Name 3",
    display: true,
    primary: false,
  },
  taxFrac_3: {
    name: "taxFrac_3",
    value: "taxFrac_3",
    alias: "Tax Frac 3",
    display: true,
    primary: false,
  },
  taxName_4: {
    name: "taxName_4",
    value: "taxName_4",
    alias: "Tax Name 4",
    display: true,
    primary: false,
  },
  taxFrac_4: {
    name: "taxFrac_4",
    value: "taxFrac_4",
    alias: "Tax Frac 4",
    display: true,
    primary: false,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "owner",
    display: false,
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: true,
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: true,
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: false, // temporary disabled
    primary: false,
  },
  RawStats__Reads: {
    name: "Reads",
    value: "RawStats__Reads",
    alias: "Reads",
    display: true,
    primary: false,
  },
  RawStats__Yield: {
    name: "Yield",
    value: "RawStats__Yield",
    alias: "Yield",
    display: true,
    primary: false,
  },
  RawStats__GeeCee: {
    name: "GeeCee",
    value: "RawStats__GeeCee",
    alias: "GeeCee",
    display: true,
    primary: false,
  },
  RawStats__MinLen: {
    name: "MinLen",
    value: "Raw_stats__MinLen",
    alias: "MinLen",
    display: true,
    primary: false,
  },
  RawStats__AvgLen: {
    name: "AvgLen",
    value: "RawStats__AvgLen",
    alias: "AvgLen",
    display: true,
    primary: false,
  },
  RawStats__MaxLen: {
    name: "MaxLen",
    value: "RawStats__MaxLen",
    alias: "MaxLen",
    display: true,
    primary: false,
  },
  RawStats__AvgQual: {
    name: "AvgQual",
    value: "RawStats__AvgQual",
    alias: "AvgQual",
    display: true,
    primary: false,
  },
  RawStats__ErrQual: {
    name: "ErrQual",
    value: "RawStats__ErrQual",
    alias: "ErrQual",
    display: true,
    primary: false,
  },
  RawStats__Ambiguous: {
    name: "Ambiguous",
    value: "RawStats__Ambiguous",
    alias: "Ambiguous",
    display: true,
    primary: false,
  },
  QcStats__Reads: {
    name: "Reads",
    value: "QcStats__Reads",
    alias: "Reads",
    display: true,
    primary: false,
  },
  QcStats__Yield: {
    name: "Yield",
    value: "QcStats__Yield",
    alias: "Yield",
    display: true,
    primary: false,
  },
  QcStats__GeeCee: {
    name: "GeeCee",
    value: "QcStats__GeeCee",
    alias: "GeeCee",
    display: true,
    primary: false,
  },
  QcStats__MinLen: {
    name: "MinLen",
    value: "QcStats__MinLen",
    alias: "MinLen",
    display: true,
    primary: false,
  },
  QcStats__AvgLen: {
    name: "AvgLen",
    value: "QcStats__AvgLen",
    alias: "AvgLen",
    display: true,
    primary: false,
  },
  QcStats__MaxLen: {
    name: "MaxLen",
    value: "QcStats__MaxLen",
    alias: "MaxLen",
    display: true,
    primary: false,
  },
  QcStats__AvgQual: {
    name: "AvgQual",
    value: "QcStats__AvgQual",
    alias: "AvgQual",
    display: true,
    primary: false,
  },
  QcStats__ErrQual: {
    name: "ErrQual",
    value: "QcStats__ErrQual",
    alias: "ErrQual",
    display: true,
    primary: false,
  },
  QcStats__Ambiguous: {
    name: "Ambiguous",
    value: "QcStats__Ambiguous",
    alias: "Ambiguous",
    display: true,
    primary: false,
  },
};
