/**
 * @author Jongil Yoon
 * @email jiysait@gmail.com
 * @create date 2021-07-25 14:52:52
 * @modify date 2021-07-25 14:52:52
 * @desc [description]
 */

/**
 * name: The original name of a data field
 * value: A value must reflect hierarchical structure
 * alias: A name will be displayed in the frontend app
 * display: A value indicates a type of display [visible, hidden, none].
 * primary: A value indicates whether a column is primary or not.
 */
export const CUSTOM_HEADER_ASSEMBLY = {
  id: {
    name: "id",
    value: "id",
    alias: "Sample ID",
    display: "visible",
    primary: true,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  sequence: {
    name: "sequence",
    value: "sequence",
    alias: "Sequence",
    display: "none",
    primary: false,
  },
  sequence__project__id: {
    name: "id",
    value: "sequence__project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  sequence__project__title: {
    name: "title",
    value: "sequence__project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  sequence__LibrarySource: {
    name: "LibrarySource",
    value: "sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  sequence__SequencerModel: {
    name: "SequencerModel",
    value: "sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "visible",
    primary: false,
  },
  sequence__CenterName: {
    name: "CenterName",
    value: "sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  count: {
    name: "count",
    value: "count",
    alias: "Count",
    display: "visible",
    primary: false,
  },
  bp: {
    name: "bp",
    value: "bp",
    alias: "BP.",
    display: "visible",
    primary: false,
  },
  Ns: {
    name: "Ns",
    value: "Ns",
    alias: "Ns.",
    display: "visible",
    primary: false,
  },
  gaps: {
    name: "gaps",
    value: "gaps",
    alias: "Gaps",
    display: "visible",
    primary: false,
  },
  min: {
    name: "min",
    value: "min",
    alias: "Min.",
    display: "visible",
    primary: false,
  },
  max: {
    name: "Max",
    value: "max",
    alias: "Max.",
    display: "visible",
    primary: false,
  },
  avg: {
    name: "avg",
    value: "avg",
    alias: "Avg.",
    display: "visible",
    primary: false,
  },
  N50: {
    name: "N50",
    value: "N50",
    alias: "N50",
    display: "visible",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Seqtype",
    display: "none",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
};

export const CUSTOM_HEADER_ANNOTATION = {
  id: {
    name: "id",
    value: "id",
    alias: "ID",
    display: "none",
    primary: true,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  assembly: {
    name: "assembly",
    value: "assembly",
    alias: "Sample ID",
    display: "visible",
    primary: false,
  },
  assembly__sequence__project__id: {
    name: "id",
    value: "assembly__sequence__project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  assembly__sequence__project__title: {
    name: "title",
    value: "assembly__sequence__project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibrarySource: {
    name: "LibrarySource",
    value: "assembly__sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "assembly__sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  assembly__sequence__SequencerModel: {
    name: "SequencerModel",
    value: "assembly__sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "none",
    primary: false,
  },
  assembly__sequence__CenterName: {
    name: "CenterName",
    value: "assembly__sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  seqid: {
    name: "seqid",
    value: "seqid",
    alias: "Contig ID",
    display: "visible",
    primary: false,
  },
  source: {
    name: "source",
    value: "source",
    alias: "Source",
    display: "visible",
    primary: false,
  },
  ftype: {
    name: "ftype",
    value: "ftype",
    alias: "Feature Type",
    display: "visible",
    primary: false,
  },
  start: {
    name: "start",
    value: "start",
    alias: "Start",
    display: "visible",
    primary: false,
  },
  end: {
    name: "end",
    value: "end",
    alias: "End",
    display: "visible",
    primary: false,
  },
  score: {
    name: "score",
    value: "score",
    alias: "Score",
    display: "visible",
    primary: false,
  },
  strand: {
    name: "strand",
    value: "strand",
    alias: "Strand",
    display: "visible",
    primary: false,
  },
  phase: {
    name: "phase",
    value: "phase",
    alias: "Phase",
    display: "visible",
    primary: false,
  },
  attr: {
    name: "attr",
    value: "attr",
    alias: "Attr",
    display: "none",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Seqtype",
    display: "none",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
  attr__tag_0: {
    name: "attr__tag_0",
    value: "attr__tag_0",
    alias: "Tag 0",
    display: "visible",
    primary: false,
  },
  attr__value_0: {
    name: "attr__value_0",
    value: "attr__value_0",
    alias: "Value 0",
    display: "visible",
    primary: false,
  },
  attr__tag_1: {
    name: "attr__tag_1",
    value: "attr__tag_1",
    alias: "Tag 1",
    display: "visible",
    primary: false,
  },
  attr__value_1: {
    name: "attr__value_1",
    value: "attr__value_1",
    alias: "Value 1",
    display: "visible",
    primary: false,
  },
  attr__tag_2: {
    name: "attr__tag_2",
    value: "attr__tag_2",
    alias: "Tag 2",
    display: "visible",
    primary: false,
  },
  attr__value_2: {
    name: "attr__value_2",
    value: "attr__value_2",
    alias: "Value 2",
    display: "visible",
    primary: false,
  },
  attr__tag_3: {
    name: "attr__tag_3",
    value: "attr__tag_3",
    alias: "Tag 3",
    display: "visible",
    primary: false,
  },
  attr__value_3: {
    name: "attr__value_3",
    value: "attr__value_3",
    alias: "Value 3",
    display: "visible",
    primary: false,
  },
  attr__tag_4: {
    name: "attr__tag_4",
    value: "attr__tag_4",
    alias: "Tag 4",
    display: "visible",
    primary: false,
  },
  attr__value_4: {
    name: "attr__value_4",
    value: "attr__value_4",
    alias: "Value 4",
    display: "visible",
    primary: false,
  },
};

export const CUSTOM_HEADER_MLST = {
  id: {
    name: "id",
    value: "id",
    alias: "Sample ID",
    display: "visible",
    primary: true,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  assembly: {
    name: "assembly",
    value: "assembly",
    alias: "Assembly",
    display: "none",
    primary: false,
  },
  assembly__sequence__project__id: {
    name: "id",
    value: "assembly__sequence__project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  assembly__sequence__project__title: {
    name: "title",
    value: "assembly__sequence__project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibrarySource: {
    name: "LibrarySource",
    value: "assembly__sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "assembly__sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  assembly__sequence__SequencerModel: {
    name: "SequencerModel",
    value: "assembly__sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "none",
    primary: false,
  },
  assembly__sequence__CenterName: {
    name: "CenterName",
    value: "assembly__sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Seqtype",
    display: "none",
    primary: false,
  },
  scheme: {
    name: "scheme",
    value: "scheme",
    alias: "Scheme",
    display: "visible",
    primary: false,
  },
  st: {
    name: "st",
    value: "st",
    alias: "ST.",
    display: "visible",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
  profile__locus_0: {
    name: "locus_0",
    value: "profile__locus_0",
    alias: "Locus 0",
    display: "visible",
    primary: false,
  },
  profile__allele_0: {
    name: "allele_0",
    value: "profile__allele_0",
    alias: "Allele 0",
    display: "visible",
    primary: false,
  },
  profile__locus_1: {
    name: "locus_1",
    value: "profile__locus_1",
    alias: "Locus 1",
    display: "visible",
    primary: false,
  },
  profile__allele_1: {
    name: "allele_ 1",
    value: "profile__allele_1",
    alias: "Allele 1",
    display: "visible",
    primary: false,
  },
  profile__locus_2: {
    name: "locus_2",
    value: "profile__locus_2",
    alias: "Locus 2",
    display: "visible",
    primary: false,
  },
  profile__allele_2: {
    name: "allele_2",
    value: "profile__allele_2",
    alias: "Allele 2",
    display: "visible",
    primary: false,
  },
  profile__locus_3: {
    name: "locus_3",
    value: "profile__locus_3",
    alias: "Locus 3",
    display: "visible",
    primary: false,
  },
  profile__allele_3: {
    name: "allele_3",
    value: "profile__allele_3",
    alias: "Allele 3",
    display: "visible",
    primary: false,
  },
  profile__locus_4: {
    name: "locus_4",
    value: "profile__locus_4",
    alias: "Locus 4",
    display: "visible",
    primary: false,
  },
  profile__allele_4: {
    name: "allele_4",
    value: "profile__allele_4",
    alias: "Allele 4",
    display: "visible",
    primary: false,
  },
  profile__locus_5: {
    name: "locus_5",
    value: "profile__locus_5",
    alias: "Locus 5",
    display: "visible",
    primary: false,
  },
  profile__allele_5: {
    name: "allele_5",
    value: "profile__allele_5",
    alias: "Allele 5",
    display: "visible",
    primary: false,
  },
  profile__locus_6: {
    name: "locus_6",
    value: "profile__locus_6",
    alias: "Locus 6",
    display: "visible",
    primary: false,
  },
  profile__allele_6: {
    name: "allele_6",
    value: "profile__allele_6",
    alias: "Allele 6",
    display: "visible",
    primary: false,
  },
  profile__locus_7: {
    name: "locus_7",
    value: "profile__locus_7",
    alias: "Locus 7",
    display: "visible",
    primary: false,
  },
  profile__allele_7: {
    name: "allele_7",
    value: "profile__allele_7",
    alias: "Allele 7",
    display: "visible",
    primary: false,
  },
};

export const CUSTOM_HEADER_RESISTOME = {
  id: {
    name: "id",
    value: "id",
    alias: "Sample ID",
    display: "visible",
    primary: true,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  assembly: {
    name: "assembly",
    value: "assembly",
    alias: "Assembly",
    display: "none",
    primary: false,
  },
  assembly__sequence__project__id: {
    name: "id",
    value: "assembly__sequence__project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  assembly__sequence__project__title: {
    name: "title",
    value: "assembly__sequence__project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibrarySource: {
    name: "LibrarySource",
    value: "assembly__sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "assembly__sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  assembly__sequence__SequencerModel: {
    name: "SequencerModel",
    value: "assembly__sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "none",
    primary: false,
  },
  assembly__sequence__CenterName: {
    name: "CenterName",
    value: "assembly__sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Seqtype",
    display: "none",
    primary: false,
  },
  num_found: {
    name: "num_found",
    value: "num_found",
    alias: "# Found",
    display: "visible",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
  profile__geneName_0: {
    name: "profile__geneName_0",
    value: "profile__geneName_0",
    alias: "Gene Name 0",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_0: {
    name: "profile__pctCoverage_0",
    value: "profile__pctCoverage_0",
    alias: "Percent of coverage 0",
    display: "visible",
    primary: false,
  },
  profile__geneName_1: {
    name: "profile__geneName_1",
    value: "profile__geneName_1",
    alias: "Gene Name 1",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_1: {
    name: "profile__pctCoverage_1",
    value: "profile__pctCoverage_1",
    alias: "Percent of coverage 1",
    display: "visible",
    primary: false,
  },
  profile__geneName_2: {
    name: "profile__geneName_2",
    value: "profile__geneName_2",
    alias: "Gene Name 2",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_2: {
    name: "profile__pctCoverage_2",
    value: "profile__pctCoverage_2",
    alias: "Percent of coverage 2",
    display: "visible",
    primary: false,
  },
};

export const CUSTOM_HEADER_VIRULOME = {
  id: {
    name: "id",
    value: "id",
    alias: "Sample ID",
    display: "visible",
    primary: true,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  assembly: {
    name: "assembly",
    value: "assembly",
    alias: "Assembly",
    display: "none",
    primary: false,
  },
  assembly__sequence__project__id: {
    name: "id",
    value: "assembly__sequence__project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  assembly__sequence__project__title: {
    name: "id",
    value: "assembly__sequence__project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibrarySource: {
    name: "id",
    value: "assembly__sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  assembly__sequence__LibraryLayout: {
    name: "id",
    value: "assembly__sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  assembly__sequence__SequencerModel: {
    name: "id",
    value: "assembly__sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "none",
    primary: false,
  },
  assembly__sequence__CenterName: {
    name: "id",
    value: "assembly__sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "Seqtype",
    display: "none",
    primary: false,
  },
  num_found: {
    name: "num_found",
    value: "num_found",
    alias: "# Found",
    display: "visible",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
  profile__geneName_0: {
    name: "profile__geneName_0",
    value: "profile__geneName_0",
    alias: "Gene Name 0",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_0: {
    name: "profile__pctCoverage_0",
    value: "profile__pctCoverage_0",
    alias: "Percent of coverage 0",
    display: "visible",
    primary: false,
  },
  profile__geneName_1: {
    name: "profile__geneName_1",
    value: "profile__geneName_1",
    alias: "Gene Name 1",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_1: {
    name: "profile__pctCoverage_1",
    value: "profile__pctCoverage_1",
    alias: "Percent of coverage 1",
    display: "visible",
    primary: false,
  },
  profile__geneName_2: {
    name: "profile__geneName_2",
    value: "profile__geneName_2",
    alias: "Gene Name 2",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_2: {
    name: "profile__pctCoverage_2",
    value: "profile__pctCoverage_2",
    alias: "Percent of coverage 2",
    display: "visible",
    primary: false,
  },
  profile__geneName_3: {
    name: "profile__geneName_3",
    value: "profile__geneName_3",
    alias: "Gene Name 3",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_3: {
    name: "profile__pctCoverage_3",
    value: "profile__pctCoverage_3",
    alias: "Percent of coverage 3",
    display: "visible",
    primary: false,
  },
  profile__geneName_4: {
    name: "profile__geneName_4",
    value: "profile__geneName_4",
    alias: "Gene Name 4",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_4: {
    name: "profile__pctCoverage_4",
    value: "profile__pctCoverage_4",
    alias: "Percent of coverage 4",
    display: "visible",
    primary: false,
  },
  profile__geneName_5: {
    name: "profile__geneName_5",
    value: "profile__geneName_5",
    alias: "Gene Name 5",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_5: {
    name: "profile__pctCoverage_5",
    value: "profile__pctCoverage_5",
    alias: "Percent of coverage 5",
    display: "visible",
    primary: false,
  },
  profile__geneName_6: {
    name: "profile__geneName_6",
    value: "profile__geneName_6",
    alias: "Gene Name 6",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_6: {
    name: "profile__pctCoverage_6",
    value: "profile__pctCoverage_6",
    alias: "Percent of coverage 6",
    display: "visible",
    primary: false,
  },
  profile__geneName_7: {
    name: "profile__geneName_7",
    value: "profile__geneName_7",
    alias: "Gene Name 7",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_7: {
    name: "profile__pctCoverage_7",
    value: "profile__pctCoverage_7",
    alias: "Percent of coverage 7",
    display: "visible",
    primary: false,
  },
  profile__geneName_8: {
    name: "profile__geneName_8",
    value: "profile__geneName_8",
    alias: "Gene Name 8",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_8: {
    name: "profile__pctCoverage_8",
    value: "profile__pctCoverage_8",
    alias: "Percent of coverage 8",
    display: "visible",
    primary: false,
  },
  profile__geneName_9: {
    name: "profile__geneName_9",
    value: "profile__geneName_9",
    alias: "Gene Name 9",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_9: {
    name: "profile__pctCoverage_9",
    value: "profile__pctCoverage_9",
    alias: "Percent of coverage 9",
    display: "visible",
    primary: false,
  },
  profile__geneName_10: {
    name: "profile__geneName_10",
    value: "profile__geneName_10",
    alias: "Gene Name 10",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_10: {
    name: "profile__pctCoverage_10",
    value: "profile__pctCoverage_10",
    alias: "Percent of coverage 10",
    display: "visible",
    primary: false,
  },
  profile__geneName_11: {
    name: "profile__geneName_11",
    value: "profile__geneName_11",
    alias: "Gene Name 11",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_11: {
    name: "profile__pctCoverage_11",
    value: "profile__pctCoverage_11",
    alias: "Percent of coverage 11",
    display: "visible",
    primary: false,
  },
  profile__geneName_12: {
    name: "profile__geneName_12",
    value: "profile__geneName_12",
    alias: "Gene Name 12",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_12: {
    name: "profile__pctCoverage_12",
    value: "profile__pctCoverage_12",
    alias: "Percent of coverage 12",
    display: "visible",
    primary: false,
  },
  profile__geneName_13: {
    name: "profile__geneName_13",
    value: "profile__geneName_13",
    alias: "Gene Name 13",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_13: {
    name: "profile__pctCoverage_13",
    value: "profile__pctCoverage_13",
    alias: "Percent of coverage 13",
    display: "visible",
    primary: false,
  },
  profile__geneName_14: {
    name: "profile__geneName_14",
    value: "profile__geneName_14",
    alias: "Gene Name 14",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_14: {
    name: "profile__pctCoverage_14",
    value: "profile__pctCoverage_14",
    alias: "Percent of coverage 14",
    display: "visible",
    primary: false,
  },
  profile__geneName_15: {
    name: "profile__geneName_15",
    value: "profile__geneName_15",
    alias: "Gene Name 15",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_15: {
    name: "profile__pctCoverage_15",
    value: "profile__pctCoverage_15",
    alias: "Percent of coverage 15",
    display: "visible",
    primary: false,
  },
  profile__geneName_16: {
    name: "profile__geneName_16",
    value: "profile__geneName_16",
    alias: "Gene Name 16",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_16: {
    name: "profile__pctCoverage_16",
    value: "profile__pctCoverage_16",
    alias: "Percent of coverage 16",
    display: "visible",
    primary: false,
  },
  profile__geneName_17: {
    name: "profile__geneName_17",
    value: "profile__geneName_17",
    alias: "Gene Name 17",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_17: {
    name: "profile__pctCoverage_17",
    value: "profile__pctCoverage_17",
    alias: "Percent of coverage 17",
    display: "visible",
    primary: false,
  },
  profile__geneName_18: {
    name: "profile__geneName_18",
    value: "profile__geneName_18",
    alias: "Gene Name 18",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_18: {
    name: "profile__pctCoverage_18",
    value: "profile__pctCoverage_18",
    alias: "Percent of coverage 18",
    display: "visible",
    primary: false,
  },
  profile__geneName_19: {
    name: "profile__geneName_19",
    value: "profile__geneName_19",
    alias: "Gene Name 19",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_19: {
    name: "profile__pctCoverage_19",
    value: "profile__pctCoverage_19",
    alias: "Percent of coverage 19",
    display: "visible",
    primary: false,
  },
  profile__geneName_20: {
    name: "profile__geneName_20",
    value: "profile__geneName_20",
    alias: "Gene Name 20",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_20: {
    name: "profile__pctCoverage_20",
    value: "profile__pctCoverage_20",
    alias: "Percent of coverage 20",
    display: "visible",
    primary: false,
  },
  profile__geneName_21: {
    name: "profile__geneName_21",
    value: "profile__geneName_21",
    alias: "Gene Name 21",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_21: {
    name: "profile__pctCoverage_21",
    value: "profile__pctCoverage_21",
    alias: "Percent of coverage 21",
    display: "visible",
    primary: false,
  },
  profile__geneName_22: {
    name: "profile__geneName_22",
    value: "profile__geneName_22",
    alias: "Gene Name 22",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_22: {
    name: "profile__pctCoverage_22",
    value: "profile__pctCoverage_22",
    alias: "Percent of coverage 22",
    display: "visible",
    primary: false,
  },
  profile__geneName_23: {
    name: "profile__geneName_23",
    value: "profile__geneName_23",
    alias: "Gene Name 23",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_23: {
    name: "profile__pctCoverage_23",
    value: "profile__pctCoverage_23",
    alias: "Percent of coverage 23",
    display: "visible",
    primary: false,
  },
  profile__geneName_24: {
    name: "profile__geneName_24",
    value: "profile__geneName_24",
    alias: "Gene Name 24",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_24: {
    name: "profile__pctCoverage_24",
    value: "profile__pctCoverage_24",
    alias: "Percent of coverage 24",
    display: "visible",
    primary: false,
  },
  profile__geneName_25: {
    name: "profile__geneName_25",
    value: "profile__geneName_25",
    alias: "Gene Name 25",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_25: {
    name: "profile__pctCoverage_25",
    value: "profile__pctCoverage_25",
    alias: "Percent of coverage 25",
    display: "visible",
    primary: false,
  },
  profile__geneName_26: {
    name: "profile__geneName_26",
    value: "profile__geneName_26",
    alias: "Gene Name 26",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_26: {
    name: "profile__pctCoverage_26",
    value: "profile__pctCoverage_26",
    alias: "Percent of coverage 26",
    display: "visible",
    primary: false,
  },
  profile__geneName_27: {
    name: "profile__geneName_27",
    value: "profile__geneName_27",
    alias: "Gene Name 27",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_27: {
    name: "profile__pctCoverage_27",
    value: "profile__pctCoverage_27",
    alias: "Percent of coverage 27",
    display: "visible",
    primary: false,
  },
  profile__geneName_28: {
    name: "profile__geneName_28",
    value: "profile__geneName_28",
    alias: "Gene Name 28",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_28: {
    name: "profile__pctCoverage_28",
    value: "profile__pctCoverage_28",
    alias: "Percent of coverage 28",
    display: "visible",
    primary: false,
  },
  profile__geneName_29: {
    name: "profile__geneName_29",
    value: "profile__geneName_29",
    alias: "Gene Name 29",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_29: {
    name: "profile__pctCoverage_29",
    value: "profile__pctCoverage_29",
    alias: "Percent of coverage 29",
    display: "visible",
    primary: false,
  },
  profile__geneName_30: {
    name: "profile__geneName_30",
    value: "profile__geneName_30",
    alias: "Gene Name 30",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_30: {
    name: "profile__pctCoverage_30",
    value: "profile__pctCoverage_30",
    alias: "Percent of coverage 30",
    display: "visible",
    primary: false,
  },
  profile__geneName_31: {
    name: "profile__geneName_31",
    value: "profile__geneName_31",
    alias: "Gene Name 31",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_31: {
    name: "profile__pctCoverage_31",
    value: "profile__pctCoverage_31",
    alias: "Percent of coverage 31",
    display: "visible",
    primary: false,
  },
  profile__geneName_32: {
    name: "profile__geneName_32",
    value: "profile__geneName_32",
    alias: "Gene Name 32",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_32: {
    name: "profile__pctCoverage_32",
    value: "profile__pctCoverage_32",
    alias: "Percent of coverage 32",
    display: "visible",
    primary: false,
  },
  profile__geneName_33: {
    name: "profile__geneName_33",
    value: "profile__geneName_33",
    alias: "Gene Name 33",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_33: {
    name: "profile__pctCoverage_33",
    value: "profile__pctCoverage_33",
    alias: "Percent of coverage 33",
    display: "visible",
    primary: false,
  },
  profile__geneName_34: {
    name: "profile__geneName_34",
    value: "profile__geneName_34",
    alias: "Gene Name 34",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_34: {
    name: "profile__pctCoverage_34",
    value: "profile__pctCoverage_34",
    alias: "Percent of coverage 34",
    display: "visible",
    primary: false,
  },
  profile__geneName_35: {
    name: "profile__geneName_35",
    value: "profile__geneName_35",
    alias: "Gene Name 35",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_35: {
    name: "profile__pctCoverage_35",
    value: "profile__pctCoverage_35",
    alias: "Percent of coverage 35",
    display: "visible",
    primary: false,
  },
  profile__geneName_36: {
    name: "profile__geneName_36",
    value: "profile__geneName_36",
    alias: "Gene Name 36",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_36: {
    name: "profile__pctCoverage_36",
    value: "profile__pctCoverage_36",
    alias: "Percent of coverage 36",
    display: "visible",
    primary: false,
  },
  profile__geneName_37: {
    name: "profile__geneName_37",
    value: "profile__geneName_37",
    alias: "Gene Name 37",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_37: {
    name: "profile__pctCoverage_37",
    value: "profile__pctCoverage_37",
    alias: "Percent of coverage 37",
    display: "visible",
    primary: false,
  },
  profile__geneName_38: {
    name: "profile__geneName_38",
    value: "profile__geneName_38",
    alias: "Gene Name 38",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_38: {
    name: "profile__pctCoverage_38",
    value: "profile__pctCoverage_38",
    alias: "Percent of coverage 38",
    display: "visible",
    primary: false,
  },
  profile__geneName_39: {
    name: "profile__geneName_39",
    value: "profile__geneName_39",
    alias: "Gene Name 39",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_39: {
    name: "profile__pctCoverage_39",
    value: "profile__pctCoverage_39",
    alias: "Percent of coverage 39",
    display: "visible",
    primary: false,
  },
  profile__geneName_40: {
    name: "profile__geneName_40",
    value: "profile__geneName_40",
    alias: "Gene Name 40",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_40: {
    name: "profile__pctCoverage_40",
    value: "profile__pctCoverage_40",
    alias: "Percent of coverage 40",
    display: "visible",
    primary: false,
  },
  profile__geneName_41: {
    name: "profile__geneName_41",
    value: "profile__geneName_41",
    alias: "Gene Name 41",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_41: {
    name: "profile__pctCoverage_41",
    value: "profile__pctCoverage_41",
    alias: "Percent of coverage 41",
    display: "visible",
    primary: false,
  },
  profile__geneName_42: {
    name: "profile__geneName_42",
    value: "profile__geneName_42",
    alias: "Gene Name 42",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_42: {
    name: "profile__pctCoverage_42",
    value: "profile__pctCoverage_42",
    alias: "Percent of coverage 42",
    display: "visible",
    primary: false,
  },
  profile__geneName_43: {
    name: "profile__geneName_43",
    value: "profile__geneName_43",
    alias: "Gene Name 43",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_43: {
    name: "profile__pctCoverage_43",
    value: "profile__pctCoverage_43",
    alias: "Percent of coverage 43",
    display: "visible",
    primary: false,
  },
  profile__geneName_44: {
    name: "profile__geneName_44",
    value: "profile__geneName_44",
    alias: "Gene Name 44",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_44: {
    name: "profile__pctCoverage_44",
    value: "profile__pctCoverage_44",
    alias: "Percent of coverage 44",
    display: "visible",
    primary: false,
  },
  profile__geneName_45: {
    name: "profile__geneName_45",
    value: "profile__geneName_45",
    alias: "Gene Name 45",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_45: {
    name: "profile__pctCoverage_45",
    value: "profile__pctCoverage_45",
    alias: "Percent of coverage 45",
    display: "visible",
    primary: false,
  },
  profile__geneName_46: {
    name: "profile__geneName_46",
    value: "profile__geneName_46",
    alias: "Gene Name 46",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_46: {
    name: "profile__pctCoverage_46",
    value: "profile__pctCoverage_46",
    alias: "Percent of coverage 46",
    display: "visible",
    primary: false,
  },
  profile__geneName_47: {
    name: "profile__geneName_47",
    value: "profile__geneName_47",
    alias: "Gene Name 47",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_47: {
    name: "profile__pctCoverage_47",
    value: "profile__pctCoverage_47",
    alias: "Percent of coverage 47",
    display: "visible",
    primary: false,
  },
  profile__geneName_48: {
    name: "profile__geneName_48",
    value: "profile__geneName_48",
    alias: "Gene Name 48",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_48: {
    name: "profile__pctCoverage_48",
    value: "profile__pctCoverage_48",
    alias: "Percent of coverage 48",
    display: "visible",
    primary: false,
  },
  profile__geneName_49: {
    name: "profile__geneName_49",
    value: "profile__geneName_49",
    alias: "Gene Name 49",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_49: {
    name: "profile__pctCoverage_49",
    value: "profile__pctCoverage_49",
    alias: "Percent of coverage 49",
    display: "visible",
    primary: false,
  },
  profile__geneName_50: {
    name: "profile__geneName_50",
    value: "profile__geneName_50",
    alias: "Gene Name 50",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_50: {
    name: "profile__pctCoverage_50",
    value: "profile__pctCoverage_50",
    alias: "Percent of coverage 50",
    display: "visible",
    primary: false,
  },
  profile__geneName_51: {
    name: "profile__geneName_51",
    value: "profile__geneName_51",
    alias: "Gene Name 51",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_51: {
    name: "profile__pctCoverage_51",
    value: "profile__pctCoverage_51",
    alias: "Percent of coverage 51",
    display: "visible",
    primary: false,
  },
  profile__geneName_52: {
    name: "profile__geneName_52",
    value: "profile__geneName_52",
    alias: "Gene Name 52",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_52: {
    name: "profile__pctCoverage_52",
    value: "profile__pctCoverage_52",
    alias: "Percent of coverage 52",
    display: "visible",
    primary: false,
  },
  profile__geneName_53: {
    name: "profile__geneName_53",
    value: "profile__geneName_53",
    alias: "Gene Name 53",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_53: {
    name: "profile__pctCoverage_53",
    value: "profile__pctCoverage_53",
    alias: "Percent of coverage 53",
    display: "visible",
    primary: false,
  },
  profile__geneName_54: {
    name: "profile__geneName_54",
    value: "profile__geneName_54",
    alias: "Gene Name 54",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_54: {
    name: "profile__pctCoverage_54",
    value: "profile__pctCoverage_54",
    alias: "Percent of coverage 54",
    display: "visible",
    primary: false,
  },
  profile__geneName_55: {
    name: "profile__geneName_55",
    value: "profile__geneName_55",
    alias: "Gene Name 55",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_55: {
    name: "profile__pctCoverage_55",
    value: "profile__pctCoverage_55",
    alias: "Percent of coverage 55",
    display: "visible",
    primary: false,
  },
  profile__geneName_56: {
    name: "profile__geneName_56",
    value: "profile__geneName_56",
    alias: "Gene Name 56",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_56: {
    name: "profile__pctCoverage_56",
    value: "profile__pctCoverage_56",
    alias: "Percent of coverage 56",
    display: "visible",
    primary: false,
  },
  profile__geneName_57: {
    name: "profile__geneName_57",
    value: "profile__geneName_57",
    alias: "Gene Name 57",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_57: {
    name: "profile__pctCoverage_57",
    value: "profile__pctCoverage_57",
    alias: "Percent of coverage 57",
    display: "visible",
    primary: false,
  },
  profile__geneName_58: {
    name: "profile__geneName_58",
    value: "profile__geneName_58",
    alias: "Gene Name 58",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_58: {
    name: "profile__pctCoverage_58",
    value: "profile__pctCoverage_58",
    alias: "Percent of coverage 58",
    display: "visible",
    primary: false,
  },
  profile__geneName_59: {
    name: "profile__geneName_59",
    value: "profile__geneName_59",
    alias: "Gene Name 59",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_59: {
    name: "profile__pctCoverage_59",
    value: "profile__pctCoverage_59",
    alias: "Percent of coverage 59",
    display: "visible",
    primary: false,
  },
  profile__geneName_60: {
    name: "profile__geneName_60",
    value: "profile__geneName_60",
    alias: "Gene Name 60",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_60: {
    name: "profile__pctCoverage_60",
    value: "profile__pctCoverage_60",
    alias: "Percent of coverage 60",
    display: "visible",
    primary: false,
  },
  profile__geneName_61: {
    name: "profile__geneName_61",
    value: "profile__geneName_61",
    alias: "Gene Name 61",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_61: {
    name: "profile__pctCoverage_61",
    value: "profile__pctCoverage_61",
    alias: "Percent of coverage 61",
    display: "visible",
    primary: false,
  },
  profile__geneName_62: {
    name: "profile__geneName_62",
    value: "profile__geneName_62",
    alias: "Gene Name 62",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_62: {
    name: "profile__pctCoverage_62",
    value: "profile__pctCoverage_62",
    alias: "Percent of coverage 62",
    display: "visible",
    primary: false,
  },
  profile__geneName_63: {
    name: "profile__geneName_63",
    value: "profile__geneName_63",
    alias: "Gene Name 63",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_63: {
    name: "profile__pctCoverage_63",
    value: "profile__pctCoverage_63",
    alias: "Percent of coverage 63",
    display: "visible",
    primary: false,
  },
  profile__geneName_64: {
    name: "profile__geneName_64",
    value: "profile__geneName_64",
    alias: "Gene Name 64",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_64: {
    name: "profile__pctCoverage_64",
    value: "profile__pctCoverage_64",
    alias: "Percent of coverage 64",
    display: "visible",
    primary: false,
  },
  profile__geneName_65: {
    name: "profile__geneName_65",
    value: "profile__geneName_65",
    alias: "Gene Name 65",
    display: "visible",
    primary: false,
  },
  profile__pctCoverage_65: {
    name: "profile__pctCoverage_65",
    value: "profile__pctCoverage_65",
    alias: "Percent of coverage 65",
    display: "visible",
    primary: false,
  },
};

export const CUSTOM_HEADER_PSUMMARY = {
  id: {
    name: "id",
    value: "id",
    alias: "Sample ID",
    display: "visible",
    primary: true,
  },
  sequence: {
    name: "sequence",
    value: "sequence",
    alias: "Sequence",
    display: "none",
    primary: false,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "Owner",
    display: "none",
    primary: false,
  },
  project__id: {
    name: "id",
    value: "project__id",
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  project__title: {
    name: "title",
    value: "project__title",
    alias: "Project Title",
    display: "none",
    primary: false,
  },
  sequence__LibrarySource: {
    name: "LibrarySource",
    value: "sequence__LibrarySource",
    alias: "Library Source",
    display: "none",
    primary: false,
  },
  sequence__LibraryLayout: {
    name: "LibraryLayout",
    value: "sequence__LibraryLayout",
    alias: "Library Layout",
    display: "none",
    primary: false,
  },
  sequence__SequencerModel: {
    name: "SequencerModel",
    value: "sequence__SequencerModel",
    alias: "Sequencer Model",
    display: "none",
    primary: false,
  },
  sequence__CenterName: {
    name: "CenterName",
    value: "sequence__CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  pct_reads_mapped: {
    name: "pct_reads_mapped",
    value: "pct_reads_mapped",
    alias: "Percent of reads mapped",
    display: "hidden",
    primary: false,
  },
  num_reads_mapped: {
    name: "num_reads_mapped",
    value: "num_reads_mapped",
    alias: "Number of reads mapped",
    display: "none",
    primary: false,
  },
  main_lin: {
    name: "main_lin",
    value: "main_lin",
    alias: "Main Lineage",
    display: "visible",
    primary: false,
  },
  sublin: {
    name: "sublin",
    value: "sublin",
    alias: "Sub-Lineage",
    display: "visible",
    primary: false,
  },
  num_dr_variants: {
    name: "num_dr_variants",
    value: "num_dr_variants",
    alias: "# Drug variants",
    display: "visible",
    primary: false,
  },
  num_other_variants: {
    name: "num_other_variants",
    value: "num_other_variants",
    alias: "# Other variants",
    display: "visible",
    primary: false,
  },
  drtype: {
    name: "drtype",
    value: "drtype",
    alias: "Type of drug",
    display: "visible",
    primary: false,
  },
  rifampicin: {
    name: "rifampicin",
    value: "rifampicin",
    alias: "Rifampicin",
    display: "visible",
    primary: false,
  },
  isoniazid: {
    name: "isoniazid",
    value: "isoniazid",
    alias: "Isoniazid",
    display: "visible",
    primary: false,
  },
  pyrazinamide: {
    name: "pyrazinamide",
    value: "pyrazinamide",
    alias: "Pyrazinamide",
    display: "visible",
    primary: false,
  },
  ethambutol: {
    name: "ethambutol",
    value: "ethambutol",
    alias: "Ethambutol",
    display: "visible",
    primary: false,
  },
  streptomycin: {
    name: "streptomycin",
    value: "streptomycin",
    alias: "Streptomycin",
    display: "visible",
    primary: false,
  },
  fluoroquinolones: {
    name: "fluoroquinolones",
    value: "fluoroquinolones",
    alias: "Fluoroquinolones",
    display: "visible",
    primary: false,
  },
  moxifloxacin: {
    name: "moxifloxacin",
    value: "moxifloxacin",
    alias: "Moxifloxacin",
    display: "visible",
    primary: false,
  },
  ofloxacin: {
    name: "ofloxacin",
    value: "ofloxacin",
    alias: "Ofloxacin",
    display: "visible",
    primary: false,
  },
  levofloxacin: {
    name: "levofloxacin",
    value: "levofloxacin",
    alias: "Levofloxacin",
    display: "visible",
    primary: false,
  },
  ciprofloxacin: {
    name: "ciprofloxacin",
    value: "ciprofloxacin",
    alias: "Ciprofloxacin",
    display: "visible",
    primary: false,
  },
  aminoglycosides: {
    name: "aminoglycosides",
    value: "aminoglycosides",
    alias: "Aminoglycosides",
    display: "visible",
    primary: false,
  },
  amikacin: {
    name: "amikacin",
    value: "amikacin",
    alias: "Amikacin",
    display: "visible",
    primary: false,
  },
  kanamycin: {
    name: "kanamycin",
    value: "kanamycin",
    alias: "Kanamycin",
    display: "visible",
    primary: false,
  },
  capreomycin: {
    name: "capreomycin",
    value: "capreomycin",
    alias: "Capreomycin",
    display: "visible",
    primary: false,
  },
  ethionamide: {
    name: "ethionamide",
    value: "ethionamide",
    alias: "Ethionamide",
    display: "visible",
    primary: false,
  },
  para_aminosalicylic_acid: {
    name: "para_aminosalicylic_acid",
    value: "para_aminosalicylic_acid",
    alias: "para_aminosalicylic_acid",
    display: "visible",
    primary: false,
  },
  cycloserine: {
    name: "cycloserine",
    value: "cycloserine",
    alias: "Cycloserine",
    display: "visible",
    primary: false,
  },
  linezolid: {
    name: "linezolid",
    value: "linezolid",
    alias: "Linezolid",
    display: "visible",
    primary: false,
  },
  bedaquiline: {
    name: "bedaquiline",
    value: "bedaquiline",
    alias: "Bedaquiline",
    display: "visible",
    primary: false,
  },
  clofazimine: {
    name: "clofazimine",
    value: "clofazimine",
    alias: "Clofazimine",
    display: "visible",
    primary: false,
  },
  delamanid: {
    name: "delamanid",
    value: "delamanid",
    alias: "Delamanid",
    display: "visible",
    primary: false,
  },

  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "DateCreated",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "LastUpdate",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
};

export const CUSTOM_HEADER_SEQUENCE = {
  id: {
    name: "id",
    value: "id",
    alias: "ID",
    display: "visible",
    primary: true,
  },
  TaxID: {
    name: "TaxID",
    value: "TaxID",
    alias: "Tax ID",
    display: "visible",
    primary: false,
  },
  ScientificName: {
    name: "ScientificName",
    value: "ScientificName",
    alias: "Scientific Name",
    display: "visible",
    primary: false,
  },
  seqtype: {
    name: "seqtype",
    value: "seqtype",
    alias: "seqtype",
    display: "none",
    primary: false,
  },
  Experiment: {
    name: "Experiment",
    value: "Experiment",
    alias: "Experiment",
    display: "visible",
    primary: false,
  },
  LibraryName: {
    name: "LibraryName",
    value: "LibraryName",
    alias: "Library Name",
    display: "visible",
    primary: false,
  },
  LibraryStrategy: {
    name: "LibraryStrategy",
    value: "LibraryStrategy",
    alias: "Library Strategy",
    display: "visible",
    primary: false,
  },
  LibrarySelection: {
    name: "LibrarySelection",
    value: "LibrarySelection",
    alias: "Library Selection",
    display: "visible",
    primary: false,
  },
  LibrarySource: {
    name: "LibrarySource",
    value: "LibrarySource",
    alias: "Library Source",
    display: "visible",
    primary: false,
  },
  LibraryLayout: {
    name: "LibraryLayout",
    value: "LibraryLayout",
    alias: "Library Layout",
    display: "visible",
    primary: false,
  },
  Platform: {
    name: "Platform",
    value: "Platform",
    alias: "Platform",
    display: "visible",
    primary: false,
  },
  SequencerModel: {
    name: "SequencerModel",
    value: "SequencerModel",
    alias: "SequencerModel",
    display: "visible",
    primary: false,
  },
  Projectid: {
    name: "Projectid",
    value: "project__id", //need to check backend
    alias: "Project ID",
    display: "visible",
    primary: false,
  },
  SampleName: {
    name: "SampleName",
    value: "SampleName",
    alias: "Sample Name",
    display: "visible",
    primary: false,
  },
  CenterName: {
    name: "CenterName",
    value: "CenterName",
    alias: "Center Name",
    display: "visible",
    primary: false,
  },
  taxName_1: {
    name: "taxName_1",
    value: "taxName_1",
    alias: "Tax Name 1",
    display: "visible",
    primary: false,
  },
  taxFrac_1: {
    name: "taxFrac_1",
    value: "taxFrac_1",
    alias: "Tax Frac 1",
    display: "visible",
    primary: false,
  },
  taxName_2: {
    name: "taxName_2",
    value: "taxName_2",
    alias: "Tax Name 2",
    display: "visible",
    primary: false,
  },
  taxFrac_2: {
    name: "taxFrac_2",
    value: "taxFrac_2",
    alias: "Tax Frac 2",
    display: "visible",
    primary: false,
  },
  taxName_3: {
    name: "taxName_3",
    value: "taxName_3",
    alias: "Tax Name 3",
    display: "visible",
    primary: false,
  },
  taxFrac_3: {
    name: "taxFrac_3",
    value: "taxFrac_3",
    alias: "Tax Frac 3",
    display: "visible",
    primary: false,
  },
  taxName_4: {
    name: "taxName_4",
    value: "taxName_4",
    alias: "Tax Name 4",
    display: "visible",
    primary: false,
  },
  taxFrac_4: {
    name: "taxFrac_4",
    value: "taxFrac_4",
    alias: "Tax Frac 4",
    display: "visible",
    primary: false,
  },
  owner: {
    name: "owner",
    value: "owner",
    alias: "owner",
    display: "none",
    primary: false,
  },
  DateCreated: {
    name: "DateCreated",
    value: "DateCreated",
    alias: "Date Created",
    display: "visible",
    primary: false,
  },
  LastUpdate: {
    name: "LastUpdate",
    value: "LastUpdate",
    alias: "Last Update",
    display: "visible",
    primary: false,
  },
  Description: {
    name: "Description",
    value: "Description",
    alias: "Description",
    display: "none",
    primary: false,
  },
  RawStats__Reads: {
    name: "Reads",
    value: "RawStats__Reads",
    alias: "Reads",
    display: "visible",
    primary: false,
  },
  RawStats__Yield: {
    name: "Yield",
    value: "RawStats__Yield",
    alias: "Yield",
    display: "visible",
    primary: false,
  },
  RawStats__GeeCee: {
    name: "GeeCee",
    value: "RawStats__GeeCee",
    alias: "GeeCee",
    display: "visible",
    primary: false,
  },
  RawStats__MinLen: {
    name: "MinLen",
    value: "RawStats__MinLen",
    alias: "MinLen",
    display: "visible",
    primary: false,
  },
  RawStats__AvgLen: {
    name: "AvgLen",
    value: "RawStats__AvgLen",
    alias: "AvgLen",
    display: "visible",
    primary: false,
  },
  RawStats__MaxLen: {
    name: "MaxLen",
    value: "RawStats__MaxLen",
    alias: "MaxLen",
    display: "visible",
    primary: false,
  },
  RawStats__AvgQual: {
    name: "AvgQual",
    value: "RawStats__AvgQual",
    alias: "AvgQual",
    display: "visible",
    primary: false,
  },
  RawStats__ErrQual: {
    name: "ErrQual",
    value: "RawStats__ErrQual",
    alias: "ErrQual",
    display: "visible",
    primary: false,
  },
  RawStats__Ambiguous: {
    name: "Ambiguous",
    value: "RawStats__Ambiguous",
    alias: "Ambiguous",
    display: "visible",
    primary: false,
  },
  QcStats__Reads: {
    name: "Reads",
    value: "QcStats__Reads",
    alias: "Reads",
    display: "visible",
    primary: false,
  },
  QcStats__Yield: {
    name: "Yield",
    value: "QcStats__Yield",
    alias: "Yield",
    display: "visible",
    primary: false,
  },
  QcStats__GeeCee: {
    name: "GeeCee",
    value: "QcStats__GeeCee",
    alias: "GeeCee",
    display: "visible",
    primary: false,
  },
  QcStats__MinLen: {
    name: "MinLen",
    value: "QcStats__MinLen",
    alias: "MinLen",
    display: "visible",
    primary: false,
  },
  QcStats__AvgLen: {
    name: "AvgLen",
    value: "QcStats__AvgLen",
    alias: "AvgLen",
    display: "visible",
    primary: false,
  },
  QcStats__MaxLen: {
    name: "MaxLen",
    value: "QcStats__MaxLen",
    alias: "MaxLen",
    display: "visible",
    primary: false,
  },
  QcStats__AvgQual: {
    name: "AvgQual",
    value: "QcStats__AvgQual",
    alias: "AvgQual",
    display: "visible",
    primary: false,
  },
  QcStats__ErrQual: {
    name: "ErrQual",
    value: "QcStats__ErrQual",
    alias: "ErrQual",
    display: "visible",
    primary: false,
  },
  QcStats__Ambiguous: {
    name: "Ambiguous",
    value: "QcStats__Ambiguous",
    alias: "Ambiguous",
    display: "visible",
    primary: false,
  },
};
